import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './style.css';

const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=url&&key?createClient(url,key):null;

const DEMOS={
 AAMF:{name:'AAMF',type:'Apporteur d’affaires',icon:'🤝',color:'#111827',kpis:[['Opportunités actives','12'],['CA potentiel','18 450 €'],['Commissions','3 240 €'],['Priorités IA','4']],stages:['Nouveau','Contacté','Intéressé','RDV','Proposition','Signé','Commission','Payé'],actions:['Nouveau prospect','Nouvelle opportunité','Ajouter partenaire','Planifier RDV'],records:[['Retail Horizon','Prospect','Proposition'],['Enterprise Delta','Opportunité','RDV'],['Prospect Gamma','Prospect','Contacté']]},
 NASCORP:{name:'NASCORP FRET COMORES',type:'Transport / Fret',icon:'🚚',color:'#0f766e',kpis:[['Commandes en cours','18'],['Conteneurs','3'],['Enlèvements','9'],['Livraisons','14']],stages:['Demande','Devis','Commande','Enlèvement','Chargement','Transit','Arrivée Moroni','Livraison','Paiement'],actions:['Nouvelle commande','Planifier enlèvement','Ajouter colis','Créer devis'],records:[['Client Paris 13','Commande','Enlèvement'],['Client Nanterre','Commande','Transit'],['Client Épinay','Client','Devis']]}
};
function App(){
 const [session,setSession]=useState(null),[auth,setAuth]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [workspace,setWorkspace]=useState('AAMF'),[tab,setTab]=useState('dashboard'),[feedback,setFeedback]=useState(''),[sent,setSent]=useState(false);
 const [theme,setTheme]=useState(()=>{try{return JSON.parse(localStorage.getItem('famkora-theme-'+workspace))||{primary:DEMOS[workspace].color,secondary:'#64748b',mode:'light'}}catch{return {primary:DEMOS[workspace].color,secondary:'#64748b',mode:'light'}}});
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('famkora-theme-'+workspace));setTheme(saved||{primary:DEMOS[workspace].color,secondary:'#64748b',mode:'light'})}catch{}},[workspace]);
 function saveTheme(next){setTheme(next);try{localStorage.setItem('famkora-theme-'+workspace,JSON.stringify(next))}catch{}}
 const cssVars={'--brand':theme.primary,'--brand-2':theme.secondary};
 useEffect(()=>{if(!supabase)return; supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[]);
 async function submit(e){e.preventDefault();setError('');setBusy(true);try{if(!supabase)throw new Error('Bêta non configurée : renseigne les variables Supabase.');let r=auth==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)throw r.error;if(auth==='signup'&&!r.data.session)setError('Compte créé. Vérifie ton e-mail puis connecte-toi.')}catch(x){setError(x.message)}finally{setBusy(false)}}
 async function logout(){await supabase?.auth.signOut();setSession(null)}
 async function sendFeedback(){if(!feedback.trim())return; if(supabase&&session){await supabase.from('beta_feedback').insert({user_id:session.user.id,workspace_slug:workspace,message:feedback})}setFeedback('');setSent(true);setTimeout(()=>setSent(false),2500)}
 if(!session)return <Auth auth={auth} setAuth={setAuth} email={email} setEmail={setEmail} password={password} setPassword={setPassword} submit={submit} busy={busy} error={error} configured={!!supabase}/>;
 const d=DEMOS[workspace];
 return <div className="shell"><aside><div className="brand">FAM<span>KORA</span><small>BETA</small></div><div className="switch"><label>Espace</label><select value={workspace} onChange={e=>{setWorkspace(e.target.value);setTab('dashboard')}}><option>AAMF</option><option>NASCORP</option></select></div><nav>{[['dashboard','⌂','Tableau de bord'],['records','▣','Données métier'],['workflow','↗','Workflow'],['search','⌕','Recherche'],['calendar','□','Agenda'],['docs','▤','Documents'],['ai','✦','Assistant IA'],['appearance','◉','Apparence'],['feedback','◌','Retour bêta']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]} {x[2]}</button>)}</nav><div className="user"><b>{session.user.email}</b><small>{d.type}</small><button onClick={logout}>Se déconnecter</button></div></aside><main style={cssVars} className={theme.mode==='dark'?'darkmode':''}><header><div><div className="eyebrow">{d.icon} {d.name}</div><h1>{tab==='dashboard'?'Bonjour, bienvenue dans votre espace.':label(tab)}</h1></div><div className="online">● En ligne</div></header>{tab==='dashboard'&&<Dashboard d={d}/>} {tab==='records'&&<Records d={d}/>} {tab==='workflow'&&<Workflow d={d}/>} {tab==='search'&&<Search d={d}/>} {tab==='calendar'&&<Calendar/>} {tab==='docs'&&<Docs/>} {tab==='ai'&&<AI d={d}/>} {tab==='appearance'&&<Appearance workspace={workspace} theme={theme} saveTheme={saveTheme} reset={()=>saveTheme({primary:DEMOS[workspace].color,secondary:'#64748b',mode:'light'})}/>} {tab==='feedback'&&<Feedback feedback={feedback} setFeedback={setFeedback} send={sendFeedback} sent={sent}/>}</main></div>
}
const label=x=>({records:'Données métier',workflow:'Workflow',search:'Recherche globale',calendar:'Agenda',docs:'Documents',ai:'Assistant IA',feedback:'Retour bêta',appearance:'Apparence'}[x]||'FAMKORA');
function Auth(p){return <div className="auth"><div className="authcard"><div className="brand big">FAM<span>KORA</span><small>BETA</small></div><h1>{p.auth==='login'?'Connexion':'Créer votre compte'}</h1><p>Votre environnement métier, dans un seul espace.</p>{!p.configured&&<div className="warning">Configuration nécessaire : connecte Supabase avant d’inviter des clients.</div>}<form onSubmit={p.submit}><input type="email" placeholder="E-mail" value={p.email} onChange={e=>p.setEmail(e.target.value)} required/><input type="password" placeholder="Mot de passe" value={p.password} onChange={e=>p.setPassword(e.target.value)} required minLength="6"/><button className="primary" disabled={p.busy}>{p.busy?'Chargement…':p.auth==='login'?'Se connecter':'Créer le compte'}</button></form>{p.error&&<div className="error">{p.error}</div>}<button className="link" onClick={()=>p.setAuth(p.auth==='login'?'signup':'login')}>{p.auth==='login'?'Créer un compte bêta':'J’ai déjà un compte'}</button></div></div>}
function Dashboard({d}){return <><section className="grid">{d.kpis.map(k=><div className="card kpi" key={k[0]}><span>{k[0]}</span><strong>{k[1]}</strong></div>)}</section><section className="two"><div className="card"><h2>Actions rapides</h2><div className="actions">{d.actions.map(a=><button key={a}>{a}<b>＋</b></button>)}</div></div><div className="card"><h2>Recommandations IA</h2><div className="rec"><b>Priorité du jour</b><p>Traiter les dossiers sans prochaine action et préparer les suivis importants.</p><button>Voir les recommandations →</button></div><div className="rec"><b>Signal</b><p>3 dossiers semblent nécessiter un suivi cette semaine.</p></div></div></section><section className="card"><h2>Votre environnement</h2><p className="muted">Les données affichées ici sont propres à cet espace. La bêta est conçue pour tester la simplicité avant l’ouverture publique.</p></section></>}
function Records({d}){return <div className="card"><div className="row"><div><h2>Enregistrements</h2><p className="muted">Exemples de données métier.</p></div><button className="primary small">＋ Ajouter</button></div><table><thead><tr><th>Nom</th><th>Type</th><th>Étape</th></tr></thead><tbody>{d.records.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td><span className="pill">{r[2]}</span></td></tr>)}</tbody></table></div>}
function Workflow({d}){return <div className="card"><h2>Pipeline</h2><div className="pipeline">{d.stages.map((s,i)=><div className="stage" key={s}><span>{i+1}</span><b>{s}</b><small>{Math.max(1,7-i)} dossiers</small></div>)}</div></div>}
function Search({d}){return <div className="card"><input className="search" placeholder={`Rechercher dans ${d.name}…`}/><div className="result"><b>Recherche intelligente</b><p>Clients, opportunités, documents, messages et actions peuvent être réunis ici.</p></div></div>}
function Calendar(){return <div className="card"><h2>Agenda</h2><div className="calendar">{['09:00','10:30','12:00','14:00','15:30','17:00'].map((x,i)=><div key={x}><b>{x}</b><span>{i%2?'Disponibilité':'Suivi / rendez-vous'}</span></div>)}</div></div>}
function Docs(){return <div className="card"><h2>Documents</h2>{['Plaquette commerciale','Contrat partenaire','Liste de chargement','Note d’enlèvement'].map(x=><div className="doc" key={x}>▤ <b>{x}</b><span>Disponible</span></div>)}</div>}
function AI({d}){return <div className="card ai"><div className="spark">✦</div><h2>Assistant IA</h2><p>Pose une question sur ton activité. En production, l’IA sera limitée aux données autorisées dans cet espace.</p><div className="chips"><button>Que dois-je faire aujourd’hui ?</button><button>Quels dossiers prioriser ?</button><button>Prépare mon suivi</button></div><div className="result"><b>Suggestion</b><p>Commence par les dossiers sans prochaine action et les échéances proches.</p></div></div>}

function Appearance({workspace,theme,saveTheme,reset}){const presets=[['FAMKORA','#111827','#64748b'],['Océan','#0369a1','#0f766e'],['Forêt','#166534','#15803d'],['Énergie','#c2410c','#b45309'],['Violet','#6d28d9','#7c3aed'],['Rose','#be185d','#9d174d']]; return <div className="card appearance"><h2>Personnaliser votre environnement</h2><p className="muted">Les couleurs sont enregistrées pour <b>{workspace}</b> uniquement. Chaque métier ou entreprise peut avoir sa propre identité visuelle.</p><div className="appearance-grid"><div><label>Couleur principale</label><div className="colorrow"><input type="color" value={theme.primary} onChange={e=>saveTheme({...theme,primary:e.target.value})}/><code>{theme.primary}</code></div></div><div><label>Couleur secondaire</label><div className="colorrow"><input type="color" value={theme.secondary} onChange={e=>saveTheme({...theme,secondary:e.target.value})}/><code>{theme.secondary}</code></div></div></div><label>Préréglages</label><div className="presets">{presets.map(x=><button key={x[0]} onClick={()=>saveTheme({...theme,primary:x[1],secondary:x[2]})}><i style={{background:x[1]}}/> {x[0]}</button>)}</div><div className="theme-options"><button className={theme.mode==='light'?'selected':''} onClick={()=>saveTheme({...theme,mode:'light'})}>☀️ Clair</button><button className={theme.mode==='dark'?'selected':''} onClick={()=>saveTheme({...theme,mode:'dark'})}>🌙 Sombre</button><button onClick={reset}>↺ Réinitialiser</button></div><div className="preview"><span style={{background:theme.primary}}>Bouton principal</span><span style={{borderColor:theme.primary,color:theme.primary}}>Élément actif</span><span style={{background:theme.secondary}}>Secondaire</span></div></div>}

function Feedback({feedback,setFeedback,send,sent}){return <div className="card feedback"><h2>Votre avis compte</h2><p>Testez sans chercher à nous faire plaisir. Dites-nous ce qui est clair, ce qui bloque et ce qui manque.</p><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Ex. : Je ne comprends pas où ajouter un nouveau client…"/><button className="primary" onClick={send}>Envoyer mon retour</button>{sent&&<div className="success">Merci, retour envoyé.</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
